### ISSUE TITLE
No Module Named qiskit_addon_cutting 01_gate_cutting_to_reduce_circuit_width

### ISSUE THREAD

**Issue by RedWyrm13** [Qiskit/qiskit-addon-cutting#668]
Hello.

Downloading and running the first circuit cutting example: 01_gate_cutting_to_reduce_circuit_width, I am getting an error in the third code block with line:

from qiskit_addon_cutting import partition_problem

saying there is no module named qiskit_addon_cutting.

I followed the installation instructions to install the circuit knitting toolbox. I have tried importing from circuit_knitting received an error saying "Cannot import name partition_problem."

Thanks for any assistance.

**Comment by garrison** [comment]
I am sorry that you encountered this error.

Please use [the tutorials on the `stable/0.7` branch](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/tree/stable/0.7/docs/circuit_cutting/tutorials) until `qiskit-addon-cutting` is released (expected [on September 10](https://github.com/Qiskit-Extensions/circuit-knitting-toolbox/milestone/14)).

An alternative would be to follow the instructions at https://qiskit-extensions.github.io/circuit-knitting-toolbox/install.html#option-2-install-from-source and install under the new name.  The problem is that you installed the stable version but are trying to use the tutorials that go with the development version.

**Comment by garrison** [comment]
By the way, did you see the note at the top of the README about the rename?  I wonder if it might be useful for me to provide the old tutorials link there as well, until the migration is complete.

**Comment by RedWyrm13** [comment]
Thank you. I did not realize I was trying to use the development version.

I looked at the read me, but I missed the part at the top. I got to the github from the link at the bottom left of this page: https://qiskit-extensions.github.io/circuit-knitting-toolbox/circuit_cutting/cutqc/tutorials/tutorial_1_automatic_cut_finding.html, so I assumed it was the stable version.

**Comment by garrison** [comment]
It is now possible to install `qiskit-addon-cutting` from PyPI.
