### ISSUE TITLE
How to run On Real IBM Quantum Computer using  qiskit_ibm_runtime import QiskitRuntimeService

### ISSUE THREAD

**Issue by naeemktk** [Qiskit/qiskit-addon-cutting#687]
how to run Circuit Knitting Toolbox 0.7.0 on Real IBM Quantum Computer using  qiskit_ibm_runtime import QiskitRuntimeService as well as local computer using sampler? means when i run on real computer it cut circuits on real computer otherwise run on local system.

**Comment by garrison** [comment]
> Circuit Knitting Toolbox 0.7.0

Why the old version?  If it's because you want to use CutQC, the following instructions may not work there.

Essentially, the cutting tutorials now phrase everything in terms of "fake backends", because if you have qiskit-ibm-runtime set up correctly, the only thing you need to do is change one of the tutorials to use a real backend, and then it will work the same but on hardware.

**Comment by naeemktk** [comment]
> > Circuit Knitting Toolbox 0.7.0
> 
> Why the old version? If it's because you want to use CutQC, the following instructions may not work there.
> 
> Essentially, the cutting tutorials now phrase everything in terms of "fake backends", because if you have qiskit-ibm-runtime set up correctly, the only thing you need to do is change one of the tutorials to use a real backend, and then it will work the same but on hardware.

i want it because i am working in it. tell me how to run it on real IBM Quantum

**Comment by garrison** [comment]
> tell me how to run it on real IBM Quantum

I think you are looking for https://docs.quantum.ibm.com/guides/execute-on-hardware
